### PR TITLE
Flam v0

### PR DESCRIPTION
**Pull request by Flaminietta**
That's the first important idea to share :-)
By the way, I cannot run your scripts, I tried but not succeeded :-(
I am new with Python, I am using Python 3.5 with Spyder 3.1.3 (Anaconda)

### CODE REVIEW

**Comment by adrinjalali** [comment]
Cool. The transformation you mentioned makes sense. These are the ones I'm already doing:

- take the original day_in_cycle as X
- take the days before the end of the cycle: This is for symptoms that happen more or less specifically some time before the period. For example ovulation
- take the proportion of the cycle as X. This ignores the cycle length, and normalizes everything based on the cycle length.

We can add your transformation, and then I plan to write a test to see which ones make more sense for each symptom, then use them.

**Comment by adrinjalali** [comment]
And for not being able to run the script, you need to be more specific, and open an issue then.

https://www.mediawiki.org/wiki/How_to_report_a_bug

**Comment by Flaminietta** [comment]
> On 16 Mar 2017, at 10:02, Adrin Jalali <notifications@github.com> wrote:
> 
> Cool. The transformation you mentioned makes sense.
> 
Nice!
> These are the ones I'm already doing:
> 
> take the original day_in_cycle as X
OK
> take the days before the end of the cycle: This is for symptoms that happen more or less specifically some time before the period. For example ovulation
But ovulation does not happen before the period, or at least not that close to (it’s 14 days before, as said). And, why do you treat the ovulation as a symptom? Among symptoms it could just be the ovulation_pain I see. Maybe my simplified sketch can help avoiding simple mistakes and be penalised by the log loss. Have a look.

Just remind that “distance from the end of the cycle” and “distance from the end of the period” may vary from cycle to cycle of the same woman (unless one is within the luteal phase). It might cause a problem when you then make predictions based on them on an averaged cycle length. But let’s see what the tests say!
> take the proportion of the cycle as X. This ignores the cycle length, and normalizes everything based on the cycle length.
I’m not quite sure what you do mean. What is exactly the proportion you take?
> We can add your transformation, and then I plan to write a test to see which ones make more sense for each symptom, then use them
> 
Would you tell me which kind of tests you do like to perform? Kind of dividing the number of cycles in a learning and testing phase and try forward predictions on the second part?

Get in touch if you like,
Flaminia

**Comment by adrinjalali** [comment]
I tried to explain here:

https://github.com/adrinjalali/clue-hackathon/issues/3

**Pull request merged**
